"""add_credit_notes

Revision ID: 1ee708f0857d
Revises: a2b3c4d5e6f7
Create Date: 2026-03-08 17:49:30.514656
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '1ee708f0857d'
down_revision: Union[str, None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_note_id', sa.String(), nullable=True),
    sa.Column('credit_note_number', sa.String(), nullable=True),
    sa.Column('original_invoice_id', sa.Integer(), nullable=False),
    sa.Column('credit_note_date', sa.Date(), nullable=True),
    sa.Column('seller_name', sa.String(), nullable=True),
    sa.Column('seller_vat_id', sa.String(), nullable=True),
    sa.Column('seller_address', sa.Text(), nullable=True),
    sa.Column('buyer_name', sa.String(), nullable=True),
    sa.Column('buyer_vat_id', sa.String(), nullable=True),
    sa.Column('buyer_address', sa.Text(), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.Column('payment_account_name', sa.String(length=70), nullable=True),
    sa.Column('buyer_reference', sa.String(length=200), nullable=True),
    sa.Column('seller_endpoint_id', sa.String(length=200), nullable=True),
    sa.Column('seller_endpoint_scheme', sa.String(length=10), nullable=True),
    sa.Column('buyer_endpoint_id', sa.String(length=200), nullable=True),
    sa.Column('buyer_endpoint_scheme', sa.String(length=10), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('xrechnung_xml_path', sa.String(), nullable=True),
    sa.Column('zugferd_pdf_path', sa.String(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['original_invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_note_number', 'organization_id', name='uq_credit_note_number_org')
    )
    op.create_index(op.f('ix_credit_notes_credit_note_date'), 'credit_notes', ['credit_note_date'], unique=False)
    op.create_index(op.f('ix_credit_notes_credit_note_id'), 'credit_notes', ['credit_note_id'], unique=True)
    op.create_index(op.f('ix_credit_notes_credit_note_number'), 'credit_notes', ['credit_note_number'], unique=False)
    op.create_index(op.f('ix_credit_notes_organization_id'), 'credit_notes', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_notes_organization_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_credit_note_number'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_credit_note_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_credit_note_date'), table_name='credit_notes')
    op.drop_table('credit_notes')
    # ### end Alembic commands ###
