"""initial

Revision ID: 562688a5d131
Revises: 
Create Date: 2026-02-23 16:26:07.738651
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '562688a5d131'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('processed', sa.Integer(), nullable=True),
    sa.Column('succeeded', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_jobs_batch_id'), 'batch_jobs', ['batch_id'], unique=True)
    op.create_table('recurring_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('next_date', sa.Date(), nullable=True),
    sa.Column('last_generated', sa.Date(), nullable=True),
    sa.Column('number_prefix', sa.String(), nullable=True),
    sa.Column('payment_days', sa.Integer(), nullable=True),
    sa.Column('seller_name', sa.String(), nullable=True),
    sa.Column('seller_vat_id', sa.String(), nullable=True),
    sa.Column('seller_address', sa.Text(), nullable=True),
    sa.Column('buyer_name', sa.String(), nullable=True),
    sa.Column('buyer_vat_id', sa.String(), nullable=True),
    sa.Column('buyer_address', sa.Text(), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.Column('payment_account_name', sa.String(length=70), nullable=True),
    sa.Column('buyer_reference', sa.String(length=200), nullable=True),
    sa.Column('seller_endpoint_id', sa.String(length=200), nullable=True),
    sa.Column('buyer_endpoint_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_invoices_template_id'), 'recurring_invoices', ['template_id'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('vat_id', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('default_account', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('invoice_count', sa.Integer(), nullable=True),
    sa.Column('total_volume', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_vat_id'), 'suppliers', ['vat_id'], unique=True)
    op.create_table('archive_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archive_id', sa.String(), nullable=True),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('archive_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_entries_archive_id'), 'archive_entries', ['archive_id'], unique=True)
    op.create_index(op.f('ix_archive_entries_invoice_id'), 'archive_entries', ['invoice_id'], unique=False)
    op.add_column('invoices', sa.Column('currency', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'currency')
    op.drop_index(op.f('ix_archive_entries_invoice_id'), table_name='archive_entries')
    op.drop_index(op.f('ix_archive_entries_archive_id'), table_name='archive_entries')
    op.drop_table('archive_entries')
    op.drop_index(op.f('ix_suppliers_vat_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_recurring_invoices_template_id'), table_name='recurring_invoices')
    op.drop_table('recurring_invoices')
    op.drop_index(op.f('ix_batch_jobs_batch_id'), table_name='batch_jobs')
    op.drop_table('batch_jobs')
    # ### end Alembic commands ###
